Repository musiqueJS/musiqueJS, pull requests merged in 2023-11, with the labels that each got.

#4 infra(docker): Create Dockerfile
  Dockerfile
Labels: infrastructure

#10 :construction: FEAT new architecture
  index.ts
  src/Note.ts
  src/Partition.ts
Labels: enhancement

#12 feat(music): Implement code from POC
  index.ts
  src/CustomAccord.ts
  src/JSONPartition.ts
  src/Note.ts
  src/NoteEnum.ts
  src/Partition.ts
Labels: documentation, enhancement, v1
